package practiceset.recursion.set01;

import java.util.ArrayList;

/*
You are given string s of length n, having m wildcard characters '?', where each wildcard character represents a single character.
Write a program which returns a list of all possible distinct strings that can be generated by replacing each wildcard character in s with either '0' or '1'.
Any string returned must not contain '?' characters, all must be replaced with either '0' or '1'.
Example One
"s": "1?10"
Output: ["1010", "1110"]
 */
public class StringsFromWildCard {

    public static void main(String[] args) {
        String s = "1?10";
        ArrayList<String> result = new ArrayList<>();
        helper(s,0,new StringBuilder(),result);
        System.out.println(result);
    }

    //time complexity is O(2^m) where m is the number of wildcards in the string
    //space complexity is O(n) where n is the length of the string
    static void helper(String s, int i, StringBuilder slate, ArrayList<String> result){

        //base case
        if(i == s.length()){
            ArrayList<String> ans = new ArrayList<>();
            ans.add(slate.toString());
            result.addAll(ans);
            return;
        }

        //if not ? then I have only one option which is to include next char into slate
        if(s.charAt(i) != '?'){
            slate.append(s.charAt(i));
            helper(s,i+1,slate,result);
            slate.deleteCharAt(slate.length()-1);
        }else{
            //now I have 2 options either '0' or '1'
            slate.append("0");
            helper(s,i+1,slate,result);
            slate.deleteCharAt(slate.length()-1);

            slate.append("1");
            helper(s,i+1,slate,result);
            slate.deleteCharAt(slate.length()-1);
        }
    }
}
